/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export declare namespace IM4mBaggage {
  export type LockedNFTStruct = {
    owner: string;
    gameId: BigNumberish;
    uuid: string;
  };

  export type LockedNFTStructOutput = [string, BigNumber, string] & {
    owner: string;
    gameId: BigNumber;
    uuid: string;
  };
}

export interface IM4mBaggageInterface extends utils.Interface {
  contractName: "IM4mBaggage";
  functions: {
    "gameBegin(uint256,string,uint256,uint256[],uint256[])": FunctionFragment;
    "gameEnd(uint256,uint256[],uint256[],uint256[],uint256[],bytes,bytes)": FunctionFragment;
    "getGameOwner(uint256)": FunctionFragment;
    "isGameSettled(address,uint256,uint256,string)": FunctionFragment;
    "lockedNFTs(uint256)": FunctionFragment;
    "setGameSignerAndOperator(uint256,address,address)": FunctionFragment;
    "transferOperator(uint256,address)": FunctionFragment;
    "transferSigner(uint256,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "gameBegin",
    values: [BigNumberish, string, BigNumberish, BigNumberish[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "gameEnd",
    values: [
      BigNumberish,
      BigNumberish[],
      BigNumberish[],
      BigNumberish[],
      BigNumberish[],
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getGameOwner",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isGameSettled",
    values: [string, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "lockedNFTs",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setGameSignerAndOperator",
    values: [BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOperator",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferSigner",
    values: [BigNumberish, string]
  ): string;

  decodeFunctionResult(functionFragment: "gameBegin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gameEnd", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getGameOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isGameSettled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lockedNFTs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setGameSignerAndOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferSigner",
    data: BytesLike
  ): Result;

  events: {
    "GameBegin(uint256,tuple)": EventFragment;
    "GameSettled(uint256,tuple)": EventFragment;
    "OperatorUpdated(uint256,address)": EventFragment;
    "SignerUpdated(uint256,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "GameBegin"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "GameSettled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OperatorUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SignerUpdated"): EventFragment;
}

export type GameBeginEvent = TypedEvent<
  [BigNumber, IM4mBaggage.LockedNFTStructOutput],
  { m4mTokenId: BigNumber; info: IM4mBaggage.LockedNFTStructOutput }
>;

export type GameBeginEventFilter = TypedEventFilter<GameBeginEvent>;

export type GameSettledEvent = TypedEvent<
  [BigNumber, IM4mBaggage.LockedNFTStructOutput],
  { m4mTokenId: BigNumber; info: IM4mBaggage.LockedNFTStructOutput }
>;

export type GameSettledEventFilter = TypedEventFilter<GameSettledEvent>;

export type OperatorUpdatedEvent = TypedEvent<
  [BigNumber, string],
  { gameId: BigNumber; operator: string }
>;

export type OperatorUpdatedEventFilter = TypedEventFilter<OperatorUpdatedEvent>;

export type SignerUpdatedEvent = TypedEvent<
  [BigNumber, string],
  { gameId: BigNumber; signer: string }
>;

export type SignerUpdatedEventFilter = TypedEventFilter<SignerUpdatedEvent>;

export interface IM4mBaggage extends BaseContract {
  contractName: "IM4mBaggage";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IM4mBaggageInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    gameBegin(
      gameId: BigNumberish,
      uuid: string,
      m4mTokenId: BigNumberish,
      inComponentIds: BigNumberish[],
      inAmounts: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    gameEnd(
      m4mTokenId: BigNumberish,
      lootIds: BigNumberish[],
      lootAmounts: BigNumberish[],
      lostIds: BigNumberish[],
      lostAmounts: BigNumberish[],
      operatorSig: BytesLike,
      gameSignerSig: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getGameOwner(
      gameId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, string] & { signer: string; operator: string }>;

    isGameSettled(
      owner: string,
      m4mTokenId: BigNumberish,
      gameId: BigNumberish,
      uuid: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    lockedNFTs(
      m4mTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, string] & {
        owner: string;
        gameId: BigNumber;
        uuid: string;
      }
    >;

    setGameSignerAndOperator(
      gameId: BigNumberish,
      gameSigner: string,
      operator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOperator(
      gameId: BigNumberish,
      newOperator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferSigner(
      gameId: BigNumberish,
      newSigner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  gameBegin(
    gameId: BigNumberish,
    uuid: string,
    m4mTokenId: BigNumberish,
    inComponentIds: BigNumberish[],
    inAmounts: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  gameEnd(
    m4mTokenId: BigNumberish,
    lootIds: BigNumberish[],
    lootAmounts: BigNumberish[],
    lostIds: BigNumberish[],
    lostAmounts: BigNumberish[],
    operatorSig: BytesLike,
    gameSignerSig: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getGameOwner(
    gameId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[string, string] & { signer: string; operator: string }>;

  isGameSettled(
    owner: string,
    m4mTokenId: BigNumberish,
    gameId: BigNumberish,
    uuid: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  lockedNFTs(
    m4mTokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, string] & {
      owner: string;
      gameId: BigNumber;
      uuid: string;
    }
  >;

  setGameSignerAndOperator(
    gameId: BigNumberish,
    gameSigner: string,
    operator: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOperator(
    gameId: BigNumberish,
    newOperator: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferSigner(
    gameId: BigNumberish,
    newSigner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    gameBegin(
      gameId: BigNumberish,
      uuid: string,
      m4mTokenId: BigNumberish,
      inComponentIds: BigNumberish[],
      inAmounts: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    gameEnd(
      m4mTokenId: BigNumberish,
      lootIds: BigNumberish[],
      lootAmounts: BigNumberish[],
      lostIds: BigNumberish[],
      lostAmounts: BigNumberish[],
      operatorSig: BytesLike,
      gameSignerSig: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    getGameOwner(
      gameId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, string] & { signer: string; operator: string }>;

    isGameSettled(
      owner: string,
      m4mTokenId: BigNumberish,
      gameId: BigNumberish,
      uuid: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    lockedNFTs(
      m4mTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, string] & {
        owner: string;
        gameId: BigNumber;
        uuid: string;
      }
    >;

    setGameSignerAndOperator(
      gameId: BigNumberish,
      gameSigner: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOperator(
      gameId: BigNumberish,
      newOperator: string,
      overrides?: CallOverrides
    ): Promise<void>;

    transferSigner(
      gameId: BigNumberish,
      newSigner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "GameBegin(uint256,tuple)"(
      m4mTokenId?: null,
      info?: null
    ): GameBeginEventFilter;
    GameBegin(m4mTokenId?: null, info?: null): GameBeginEventFilter;

    "GameSettled(uint256,tuple)"(
      m4mTokenId?: null,
      info?: null
    ): GameSettledEventFilter;
    GameSettled(m4mTokenId?: null, info?: null): GameSettledEventFilter;

    "OperatorUpdated(uint256,address)"(
      gameId?: null,
      operator?: null
    ): OperatorUpdatedEventFilter;
    OperatorUpdated(gameId?: null, operator?: null): OperatorUpdatedEventFilter;

    "SignerUpdated(uint256,address)"(
      gameId?: null,
      signer?: null
    ): SignerUpdatedEventFilter;
    SignerUpdated(gameId?: null, signer?: null): SignerUpdatedEventFilter;
  };

  estimateGas: {
    gameBegin(
      gameId: BigNumberish,
      uuid: string,
      m4mTokenId: BigNumberish,
      inComponentIds: BigNumberish[],
      inAmounts: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    gameEnd(
      m4mTokenId: BigNumberish,
      lootIds: BigNumberish[],
      lootAmounts: BigNumberish[],
      lostIds: BigNumberish[],
      lostAmounts: BigNumberish[],
      operatorSig: BytesLike,
      gameSignerSig: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getGameOwner(
      gameId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isGameSettled(
      owner: string,
      m4mTokenId: BigNumberish,
      gameId: BigNumberish,
      uuid: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    lockedNFTs(
      m4mTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setGameSignerAndOperator(
      gameId: BigNumberish,
      gameSigner: string,
      operator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOperator(
      gameId: BigNumberish,
      newOperator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferSigner(
      gameId: BigNumberish,
      newSigner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    gameBegin(
      gameId: BigNumberish,
      uuid: string,
      m4mTokenId: BigNumberish,
      inComponentIds: BigNumberish[],
      inAmounts: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    gameEnd(
      m4mTokenId: BigNumberish,
      lootIds: BigNumberish[],
      lootAmounts: BigNumberish[],
      lostIds: BigNumberish[],
      lostAmounts: BigNumberish[],
      operatorSig: BytesLike,
      gameSignerSig: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getGameOwner(
      gameId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isGameSettled(
      owner: string,
      m4mTokenId: BigNumberish,
      gameId: BigNumberish,
      uuid: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    lockedNFTs(
      m4mTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setGameSignerAndOperator(
      gameId: BigNumberish,
      gameSigner: string,
      operator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOperator(
      gameId: BigNumberish,
      newOperator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferSigner(
      gameId: BigNumberish,
      newSigner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
