/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IM4mDAO, IM4mDAOInterface } from "../IM4mDAO";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract IERC721",
        name: "nft",
        type: "address",
      },
    ],
    name: "convertibleList",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IERC721",
        name: "nft",
        type: "address",
      },
      {
        internalType: "bool",
        name: "enabled",
        type: "bool",
      },
    ],
    name: "setConvertibleList",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IM4mDAO__factory {
  static readonly abi = _abi;
  static createInterface(): IM4mDAOInterface {
    return new utils.Interface(_abi) as IM4mDAOInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IM4mDAO {
    return new Contract(address, _abi, signerOrProvider) as IM4mDAO;
  }
}
