/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IM4mBaggageWithoutRole,
  IM4mBaggageWithoutRoleInterface,
} from "../IM4mBaggageWithoutRole";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "m4mTokenId",
        type: "uint256",
      },
      {
        internalType: "uint256[]",
        name: "inComponentIds",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "inAmounts",
        type: "uint256[]",
      },
    ],
    name: "appendLock",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "m4mTokenId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "gameId",
        type: "uint256",
      },
      {
        internalType: "uint256[]",
        name: "inComponentIds",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "inAmounts",
        type: "uint256[]",
      },
    ],
    name: "lockComponents",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "m4mTokenId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "componentId",
        type: "uint256",
      },
    ],
    name: "lockedComponents",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "m4mTokenId",
        type: "uint256",
      },
    ],
    name: "lockedEmptyNFTs",
    outputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "gameId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "usedNonce",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "m4mTokenId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "nonce",
        type: "uint256",
      },
      {
        internalType: "uint256[]",
        name: "lootIds",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "lootAmounts",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "lostIds",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "lostAmounts",
        type: "uint256[]",
      },
      {
        internalType: "bytes",
        name: "operatorSig",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "gameSignerSig",
        type: "bytes",
      },
    ],
    name: "settleLoots",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "m4mTokenId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "nonce",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "tokenId",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "prepare",
            type: "bool",
          },
          {
            internalType: "string",
            name: "name",
            type: "string",
          },
          {
            internalType: "string",
            name: "symbol",
            type: "string",
          },
          {
            internalType: "uint256",
            name: "amount",
            type: "uint256",
          },
        ],
        internalType: "struct IM4mComponentsV2.PrepareAndMintParam[]",
        name: "params",
        type: "tuple[]",
      },
      {
        internalType: "bytes",
        name: "operatorSig",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "gameSignerSig",
        type: "bytes",
      },
    ],
    name: "settleNewLoots",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "m4mTokenId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "nonce",
        type: "uint256",
      },
      {
        internalType: "uint256[]",
        name: "outComponentIds",
        type: "uint256[]",
      },
      {
        internalType: "bytes",
        name: "operatorSig",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "gameSignerSig",
        type: "bytes",
      },
    ],
    name: "unlockComponents",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IM4mBaggageWithoutRole__factory {
  static readonly abi = _abi;
  static createInterface(): IM4mBaggageWithoutRoleInterface {
    return new utils.Interface(_abi) as IM4mBaggageWithoutRoleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IM4mBaggageWithoutRole {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IM4mBaggageWithoutRole;
  }
}
